name: weekly btc dca
on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  dca-buy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script
        env:
          CB_API_KEY: ${{ secrets.CB_API_KEY }}
          CB_API_SECRET: ${{ secrets.CB_API_SECRET }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python dca.py \
            --cb-api-key='${CB_API_KEY}' \
            --cb-api-secret='${CB_API_SECRET}' \
            --tg-bot-token='${TG_BOT_TOKEN}' \
            --tg-chat-id='${TG_CHAT_ID}' \
            --quote-size=1

      - name: commit logs
        run: |
          git config --global user.name 'actions bot'
          git config --global user.email 'actions@github.com'
          git add logs
          git commit -m "add logs from $(data '+%Y-%m-%d')" || echo "no changes to commit"
          git push
